version: '3.8'

services:
  loadbalancer:
    build:
      context: ./loadbalancer
    container_name: loadbalancer
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
    networks:
      - lbnet

  backend1:
    build:
      context: ./backends/simple_backend
    container_name: backend1
    command: ["./simple_backend", "9001", "Backend 1"]
    networks:
      - lbnet

  backend2:
    build:
      context: ./backends/simple_backend
    container_name: backend2
    command: ["./simple_backend", "9001", "Backend 2"]
    networks:
      - lbnet

  backend3:
    build:
      context: ./backends/echo_backend
    container_name: backend3
    command: ["./echo_backend", "9001", "Echo 3:"]
    networks:
      - lbnet

  backend4:
    build:
      context: ./backends/echo_backend
    container_name: backend4
    command: [ "./echo_backend", "9001", "Echo 4:" ]
    networks:
      - lbnet

networks:
  lbnet:
