version: '3.8'

services:
  loadbalancer:
    build:
      context: ./loadbalancer
    container_name: loadbalancer
    ports:
      - "8080:8080"
    depends_on:
      - backend1
    networks:
      - lbnet

  backend1:
    build:
      context: ./backends/simple_backend
    container_name: backend1
    ports:
      - "9001:9001"
    command: ["./simple_backend", "9001"]
    networks:
      - lbnet

  backend2:
    build:
      context: ./backends/simple_backend
    container_name: backend2
    ports:
      - "9002:9001"
    command: ["./simple_backend", "9001"]
    networks:
      - lbnet

  backend3:
    build:
      context: ./backends/echo_backend
    container_name: backend3
    ports:
      - "9003:9003"
    command: ["./echo_backend", "9003"]
    networks:
      - lbnet

networks:
  lbnet:
